feat: Initial support for Pandas timeseries backend.
pywr/pywr-next pull request #240
Opened 2024-08-07 11:05 UTC by jetuk

Basic support for loading dataframes using Pandas. This is implemented using a Python callback function that loads the dataframe using Pandas, and then converts it to Polars.

2024-08-10 06:36 UTC, Batch21 requested changes
Looks good though to get it to work with my venv I had to add the path to the site-packages folder as suggested here - https://github.com/PyO3/pyo3/discussions/3726 It looks like pyo3 doesn't yet have great support for virtual environments.

2024-08-10 06:36 UTC, Batch21 commented on pywr-schema/src/timeseries/pandas.rs
> +            println!("Loaded Pandas dataset: {}", df);
remove print statement?

2024-08-15 16:12 UTC, jetuk commented
This worked fine for me when running the tests with my virtual environment activated. However, I appreciate that may not be working for everyone. The CI has the same issue with the Rust workflows not having the correct Python libraries available. 

If this is to go ahead we might need to merge the workflows or only run some of the tests in the Python workflows.

One general option is to add a "python" feature to the schema crate that would include things like this Pandas support.

2024-09-04 15:26 UTC, jetuk commented
What do you think is the best way forward with this?

2024-10-07 14:41 UTC, jetuk commented
I've featured gated the Rust tests that need a Python environment to work. They are not currently run in the CI.

2024-10-09 11:09 UTC, merged