Feature/add reservoir node
pywr/pywr-next pull request #256
Opened 2024-09-27 12:25 UTC by s-simoncelli

Hi,

as we discussed yesterday at the dev meeting, this is the new `ReservoirNode`. Some things to highlight:

- The compensation flow is a `Link` with a `min_flow` constraint but it may be better to use a soft constraint (when the `LinkNode` with soft min constraint is ready?)
- I added an option to auto-connect the comp node to the spill component. The user can disable it and connect the nodes as they wish using the slots
- @knoxsp suggested that the bathymetry implementation differs from what's suggested in pywr-1 in [PR #1115](https://github.com/pywr/pywr/pull/1115). This node allow using either a piecewise linear interpolation or a polynomial relation. I tagged him so he can comment on this.
- The `use_max_area` to use the maximum surface area for the rainfall volume is not implemented yet because I am not sure how to get the max area from the `Metric`s in the bathymetry when the schema is built. There may be a solution I haven't thought about.

2024-10-11 07:12 UTC, s-simoncelli commented
I added the `use_max_area` option and the PR is now ready for review

2025-01-23 13:11 UTC, jetuk commented
I've merged this with latest main. I'll give it a review soon. Sorry it has taken a while to get to.

2025-03-27 13:02 UTC, jetuk requested changes
Thanks for this. It's a really cool node type to add. Apologies it has taken so long for me to review.

I've left a few comments. I think there are some fixes, and some nice to haves. I think we can park any new features or improvements in an issue or two. 

I will try to add a couple of expected test files as well.

2025-03-27 13:02 UTC, jetuk commented on pywr-schema/src/nodes/reservoir.rs
> +                let evaporation_volume_parameter = pywr_core::parameters::AggregatedParameter::new(
Nitpick: I would call this flow

2025-03-27 16:48 UTC, jetuk commented on pywr-schema/src/nodes/reservoir.rs
> +        let indices = vec![
See #362 . I suggest we just change this to an error for now. I can do an update to the regular `Storage` now which can then be merged & replicated here.

2025-05-15 16:03 UTC, jetuk commented on pywr-schema/src/nodes/reservoir.rs
> +                            "The slot '{name}' in {} is only supported when the spill node is a link",
See #379

2025-07-01 10:15 UTC, merged