fix: account for leap day when indexing daily profiles
pywr/pywr-next pull request #321
Opened 2024-12-29 21:20 UTC by Batch21

This matches the behaviour in v1

2024-12-30 14:17 UTC, jetuk requested changes
There's a couple of unused imports to remove to satisfy Clippy.

2024-12-30 14:17 UTC, jetuk commented on pywr-core/src/timestep.rs
> +    pub fn day_of_year_index(&self) -> usize {
Add a docstring explaining what this returns and how it handles leap years.

2025-01-07 07:28 UTC, Batch21 commented on pywr-core/src/timestep.rs
> +    pub fn day_of_year_index(&self) -> usize {
Done

2025-01-07 09:11 UTC, jetuk approved these changes

2025-01-07 09:12 UTC, merged