feat: Upgrade to pywr-v1-schema v0.8.0.
pywr/pywr-next pull request #66
Opened 2023-10-30 19:11 UTC by jetuk

Required implementing several new parameters:

- InterpolatedParameter
- DiscountFactorParameter
- DataFrameParameter

Conversion from Storage, Deficit and Flow parameters is now returns an error as these should become metrics in pywr-next.

Todos are left for HydropowerTarget, RollingMeanFlowNode and ScenarioWrapper parameter.

Also the control curve interpolated parameter was renamed due to a naming conflict with InterpolatedParameter.

2023-11-02 12:15 UTC, Batch21 requested changes
Couple of queries but otherwise this looks good

2023-11-02 12:57 UTC, jetuk commented on pywr-schema/src/data_tables/scalar.rs
> +    Ok(LoadedScalarTable::Three(ScalarTableThree { values }))
Hmm yes. Not sure how this is compiling!

2023-11-09 16:30 UTC, jetuk commented
This was a bit broken. I've fixed the `data_tables` module. At least to the extent it has the same functionality. It could do with completing other cases and having some extensive tests & documentation.

2023-11-25 21:11 UTC, Batch21 approved these changes
fixes look good

2023-11-25 21:56 UTC, merged